version: "3.4"
services:

  mysql-master1:
    image: mysql:5.6
    container_name: "mysql-master1"
    ports:
      - "3301:3306"
    restart: always
    volumes:
     - dv-mysql-master1-data:/var/lib/mysql
     - dv-mysql-master1-conf:/etc/mysql/mysql.conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password
 
  mysql-master2:
    image: mysql:5.6
    container_name: "mysql-master2"
    ports:
      - "3302:3306"
    restart: always
    volumes:
     - dv-mysql-master2-data:/var/lib/mysql
     - dv-mysql-master2-conf:/etc/mysql/mysql.conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dv-mysql-master1-data:
  dv-mysql-master1-conf:
  dv-mysql-master2-data:
  dv-mysql-master2-conf:
  