# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8082" (or "http://$(docker-machine ip):8082" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: 123456
# Database name: pick any name
# Database host: replace "localhost" with "mysql"

version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 8082:80
    volumes:
      - /app/ownCloud/apps:/var/www/html/apps
      - /app/ownCloud/config:/var/www/html/config
      - /app/ownCloud/data:/var/www/html/data
        
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      
      
      


   
## admin 11111111